### ISSUE TITLE
cannot load grape_oauth2

### ISSUE THREAD

**Issue by matthewhatch** [nbulaj/grape_oauth2#3]
looks like this gem is in the process of being built, but may solve a problem I'm trying to solve.  After installing the gem and requiring it in my `config.ru` like this:
```ruby
# oauth2
require 'grape_oauth2'
```
 but I'm getting the following error:
```shell
.... lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- grape_oauth2 (LoadError)
```
I'm not all that familiar with gem development, but is there something in the .gemspec. or is this something local?  more than happy to help

**Comment by nbulaj** [comment]
Hi @matthewhatch. Thanks for your response!

The problem is in the RUbegems: [gems installed by Bundler through git are not handled the same way as normal gems](http://bundler.io/git.html). You need to explicitly require bundler in the `config.ru`:

```ruby
require 'bundler/setup'
Bundler.setup
```

or run your app with `bundle exec` command:

```
> bundle exec rackup config.ru
[2016-11-19 02:35:33] INFO  WEBrick 1.3.1
[2016-11-19 02:35:33] INFO  ruby 2.3.1 (2016-04-26) [i386-mingw32]
[2016-11-19 02:35:33] INFO  WEBrick::HTTPServer#start: pid=5472 port=9292
 ```

The problem will disappear when I will publish the gem to _rubygems.org_ , currently everybody need to be accurate with the bundler.
